### ISSUE TITLE
Breaking changes in 1.2.0

### ISSUE THREAD

**Issue by kytwb** [ReedD/node-assetmanager#12]
Reverting to **1.1.2** works fine:
`Error: Unable to read "public/*/*.module.js" file (Error code: ENOENT)`
Any ideas where that could come from?

**Comment by Delphinator** [comment]
Just wasted three hours as a team of two on this. This is **incredibly** bad!

**Comment by ReedD** [comment]
Sorry guys, I reverted the accepted PR. 1.2.1 is now back to the way 1.1.2 was.

**Comment by inca** [comment]
I am real sorry about that, still can't figure what the problem is :neutral_face:

@kytwb @Delphinator Could you guys please provide us with more info about your failures?

**Comment by inca** [comment]
OK, my bad. Will #13 compensate for those three hours? :)

**Comment by Delphinator** [comment]
I certainly like #13! Very good idea to add tests to avoid this mess in the future.

**Comment by kytwb** [comment]
Thanks for fixing it @inca

**Comment by ReedD** [comment]
@Delphinator  and @kytwb can you confirm that #13 doesn't break your current projects?

**Comment by Delphinator** [comment]
@ReedD It works just like `1.1.2` did.

**Comment by kytwb** [comment]
Same here, LGTM.

**Comment by kytwb** [comment]
Looks like I still have a problem with external assets `http://`, `https://` or just `//`.
