### ISSUE TITLE
Performance bug: MD5 for ALL files in EVERY request... Seriously?

### ISSUE THREAD

**Issue by agentsib** [ReedD/node-assetmanager#16]
Hi.

Library is awesome, but it has one smaaaaall performance bug...

In prodaction environment for ***EVERY*** request (even for static files) library calculate MD5 for ***ALL*** sorces assets files. I replaced one file to another (20М just for fun) and server has gone mad.

At high load, even with small files, it's very critical.

Solution: i think best way use in url hash last modify or MD5 from size and last modify assets files (NOT sources). You can chage sources, but in productionfile does not change. Why you need change hash?

Thanks.

**Comment by ReedD** [comment]
If it's running every request then I believe you have it misconfigured. You should place the `process` function outside of any middleware and/or route functions. It should only run on your scripts startup.

**Comment by agentsib** [comment]
Indeed, I had to do so. Sorry.
