### ISSUE TITLE
Fingerprinting instead of random cachebust strings

### ISSUE THREAD

**Issue by inca** [ReedD/node-assetmanager#9]
It is often necessary to preserve cachebust strings when no modifications actually occurred to specific assets. A good approach for production is to read a file (or remote resource), calculate an MD5 digest (or similar) and take a handful of first characters.

This could be done synchronously, since most apps would require fingerprinting only in production (or in build scripts).

**Comment by xizhao** [comment]
+1, fingerprinting is a must for most production apps.  Also cachebusting even in dev is useful -- maybe setting a no-cache header in dev could be a good alternative.  I would prefer cachebusting in dev by maybe having a grunt hook on watch figure out which files to re-hash.

**Comment by ReedD** [comment]
The last PR for this didn't work and I had to revert it (#12) . I'm happy to add this if somebody is able to fix it though.
